name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Navigate to Project Directory
        working-directory: ApdsPart2/ApdsPart2
        run: |
          echo "Switched to the correct project directory"

      - name: Install dependencies
        run: npm install
        working-directory: ApdsPart2/ApdsPart2

      - name: Run Tests
        run: npm test
        working-directory: ApdsPart2/ApdsPart2
