name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Use your GitHub secret
        run: |
          npx sonar-scanner \
            -Dsonar.organization=Leyaine \
            -Dsonar.projectKey=Leyaine_APDS_Part2 \
            -Dsonar.sources=.
