# .github/workflows/sonarcloud.yml
name: SonarCloud Analysis

# Trigger the workflow on pushes to the main branch or pull requests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # Use the correct distribution for Java setup
          java-version: '11'       # Specify the Java version if using Java

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.7.0.2747/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          export PATH=$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH
          echo "Checking SonarScanner version:"
          sonar-scanner --version  # Verify SonarScanner installation

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Use your GitHub secret
        run: |
          sonar-scanner -X -Dsonar.organization=Leyaine \
                        -Dsonar.projectKey=Leyaine_APDS_Part2 \
                        -Dsonar.login=$SONAR_TOKEN
